require_relative 'base_report'
require_relative 'category_by_year'
require_relative 'monthly_spend'
require_relative 'consolidated_monthly_spend'
require_relative 'monthly_balance'
require_relative 'miscellaneous_items'
